### ISSUE TITLE
`JobOptions.LeaveSourceStreamOpen` has no effect.

### ISSUE THREAD

**Issue by stakx** [imazen/lightresize#2]
`JobOptions.LeaveSourceStreamOpen` does not do what it promises. Even when this option is passed to the `ResizeJob.Build` method, the source stream will be disposed. The following (abbreviated) program demonstrates this:

``` csharp
// using Imazen.LightResize;
// using System.Diagnostics;
// using System.Drawing;
// using System.Drawing.Imaging;
// using System.IO;

using (var sourceStream = new MemoryStream())
{
    using (var bitmap = new Bitmap(10, 10))
    {
        bitmap.Save(sourceStream, ImageFormat.Png);
    }
    var resize = new ResizeJob { Width = 5, Height = 5 };
    var targetStream = new MemoryStream();
    Debug.Assert(sourceStream.CanSeek && sourceStream.CanRead); // this is fine.
    resize.Build(sourceStream, targetStream, JobOptions.LeaveSourceStreamOpen);
    Debug.Assert(sourceStream.CanSeek && sourceStream.CanRead); // this fails!
}
```

The first assertion (immediately preceding the call to `ResizeJob.Build`) will succeed. The exact same assertion after the resize fails; it should not.

**Comment by lilith** [comment]
Thanks for the fix!

**Comment by stakx** [comment]
I'm glad to help. Thanks for this small but immensely useful library!
