### ISSUE TITLE
Build output is placed outside of the main solution directory

### ISSUE THREAD

**Issue by stakx** [imazen/lightresize#3]
Building the main project (`Imazen.LightResize`) will place the output assembly outside of the project directory, namely in `..\..\dlls\{BuildConfiguration}`... which is somewhat unusual and not what most developers would expect.

I recommend that the solution structure of this project be normalized, i.e.:
- that a solution file is added;
- that all projects are moved to separate subdirectories; and
- that each project's output is placed in its own `bin\{BuildConfiguration}` subdirectory.

**Comment by stakx** [comment]
Closing this issue for now, as I suspect you might have gone on to work on other projects.

**Comment by lilith** [comment]
This is the first notification from this project I've actually seen. I'm not sure why notifications were disabled. 

I had no idea anyone was using this. Would you like push access?

**Comment by stakx** [comment]
I've been using this small library at my workplace both in legacy server-side ASP.NET code (yeah, I know...) as well as in legacy Winforms clients to work around some memory leak issues. A small library, but still very useful.

I'd be happy to clean up the code a little, and possibly publish it as a NuGet package, if that's OK with you?

**Comment by lilith** [comment]
Sounds great! Ping me at support@imageresizing.net if you need anything. I sometimes get 300+ github notifications per day, and I miss a lot of them. This repo (for unknown reasons) wasn't even enabled....

**Comment by stakx** [comment]
Fixed by commit 2bc19b5677c26c9e15b12e96f1e86fbd7ad52fb5.
